// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(RustLiveKitUniFFI)
    import RustLiveKitUniFFI
#endif

private extension RustBuffer {
    /// Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len: 0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_livekit_datatrack_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    /// Frees the buffer in place.
    /// The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_livekit_datatrack_rustbuffer_free(self, $0) }
    }
}

private extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

private extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

private func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

/// Reads an integer at the current offset, in big-endian order, and advances
/// the offset on success. Throws if reading the integer would move the
/// offset past the end of the buffer.
private func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset ..< reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value) { reader.data.copyBytes(to: $0, from: range) }
    reader.offset = range.upperBound
    return value.bigEndian
}

/// Reads an arbitrary number of bytes, to be used to read
/// raw bytes, this is useful when lifting strings
private func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> [UInt8] {
    let range = reader.offset ..< (reader.offset + count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer { buffer in
        reader.data.copyBytes(to: buffer, from: range)
    }
    reader.offset = range.upperBound
    return value
}

/// Reads a float at the current offset.
private func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    try Float(bitPattern: readInt(&reader))
}

/// Reads a float at the current offset.
private func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    try Double(bitPattern: readInt(&reader))
}

/// Indicates if the offset has reached the end of the buffer.
private func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

private func createWriter() -> [UInt8] {
    []
}

private func writeBytes(_ writer: inout [UInt8], _ byteArr: some Sequence<UInt8>) {
    writer.append(contentsOf: byteArr)
}

/// Writes an integer in big-endian order.
///
/// Warning: make sure what you are trying to write
/// is in the correct type!
private func writeInt(_ writer: inout [UInt8], _ value: some FixedWidthInteger) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

private func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

private func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

/// Protocol for types that transfer other types across the FFI. This is
/// analogous to the Rust trait of the same name.
private protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

/// Types conforming to `Primitive` pass themselves directly over the FFI.
private protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType {}

extension FfiConverterPrimitive {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> FfiType {
        value
    }
}

/// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
/// Used for complex types where it's hard to write a custom lift/lower.
private protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
        var writer = createWriter()
        write(value, into: &writer)
        return RustBuffer(bytes: writer)
    }
}

/// An error type for FFI errors. These errors occur at the UniFFI level, not
/// the library level.
private enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    var errorDescription: String? {
        switch self {
        case .bufferOverflow: "Reading the requested value would read past the end of the buffer"
        case .incompleteData: "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: "The object in the handle map has been dropped already"
        case let .rustPanic(message): message
        }
    }
}

private extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        lock()
        defer { self.unlock() }
        return try f()
    }
}

private let CALL_SUCCESS: Int8 = 0
private let CALL_ERROR: Int8 = 1
private let CALL_UNEXPECTED_ERROR: Int8 = 2
private let CALL_CANCELLED: Int8 = 3

private extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T>(
    _ errorHandler: @escaping (RustBuffer) throws -> some Swift.Error,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T
) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> some Swift.Error)?
) throws -> T {
    uniffiEnsureLivekitDatatrackInitialized()
    var callStatus = RustCallStatus()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> some Swift.Error)?
) throws {
    switch callStatus.code {
    case CALL_SUCCESS:
        return

    case CALL_ERROR:
        if let errorHandler {
            throw try errorHandler(callStatus.errorBuf)
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.unexpectedRustCallError
        }

    case CALL_UNEXPECTED_ERROR:
        // When the rust code sees a panic, it tries to construct a RustBuffer
        // with the message.  But if that code panics, then it just sends back
        // an empty buffer.
        if callStatus.errorBuf.len > 0 {
            throw try UniffiInternalError.rustPanic(FfiConverterString.lift(callStatus.errorBuf))
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.rustPanic("Rust panic")
        }

    case CALL_CANCELLED:
        fatalError("Cancellation not supported yet")

    default:
        throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void
) {
    do {
        try writeReturn(makeCall())
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> Void,
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

// Initial value and increment amount for handles.
// These ensure that SWIFT handles always have the lowest bit set
private let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
private let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

private final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            doInsert(obj)
        }
    }

    /// Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

    func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        map.count
    }
}

/// Public interface members begin here.
/// Magic number for the Rust proxy to call using the same mechanism as every other method,
/// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        try lift(readInt(&buf))
    }

    static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    static func lower(_ value: String) -> RustBuffer {
        value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return try String(bytes: readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
private struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return try Data(readBytes(&buf, count: Int(len)))
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}

/**
 * Provider for decrypting payloads for E2EE.
 */
public protocol DecryptionProvider: AnyObject, Sendable {
    /**
     * Decrypts the given payload received from a remote participant.
     *
     * Sender identity is required in order for the proper key to be used
     * for decryption.

     */
    func decrypt(payload: EncryptedPayload, senderIdentity: String) throws -> Bytes
}

/**
 * Provider for decrypting payloads for E2EE.
 */
open class DecryptionProviderImpl: DecryptionProvider, @unchecked Sendable {
    fileprivate let handle: UInt64

    // Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public required init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public init(noHandle _: NoHandle) {
        handle = 0
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func uniffiCloneHandle() -> UInt64 {
        try! rustCall { uniffi_livekit_datatrack_fn_clone_decryptionprovider(self.handle, $0) }
    }

    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_livekit_datatrack_fn_free_decryptionprovider(handle, $0) }
    }

    /**
     * Decrypts the given payload received from a remote participant.
     *
     * Sender identity is required in order for the proper key to be used
     * for decryption.

     */
    open func decrypt(payload: EncryptedPayload, senderIdentity: String) throws -> Bytes {
        try FfiConverterTypeBytes_lift(rustCallWithError(FfiConverterTypeDecryptionError_lift) {
            uniffi_livekit_datatrack_fn_method_decryptionprovider_decrypt(
                self.uniffiCloneHandle(),
                FfiConverterTypeEncryptedPayload_lower(payload),
                FfiConverterString.lower(senderIdentity), $0
            )
        })
    }
}

/// Put the implementation in a struct so we don't pollute the top-level namespace
private enum UniffiCallbackInterfaceDecryptionProvider {
    /// Create the VTable using a series of closures.
    /// Swift automatically converts these into C callback functions.
    ///
    /// Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceDecryptionProvider = .init(
        uniffiFree: { (uniffiHandle: UInt64) in
            do {
                try FfiConverterTypeDecryptionProvider.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface DecryptionProvider: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterTypeDecryptionProvider.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface DecryptionProvider: handle missing in uniffiClone")
            }
        },
        decrypt: { (
            uniffiHandle: UInt64,
            payload: RustBuffer,
            senderIdentity: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> Bytes in
                guard let uniffiObj = try? FfiConverterTypeDecryptionProvider.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.decrypt(
                    payload: FfiConverterTypeEncryptedPayload_lift(payload),
                    senderIdentity: FfiConverterString.lift(senderIdentity)
                )
            }

            let writeReturn = { uniffiOutReturn.pointee = FfiConverterTypeBytes_lower($0) }
            uniffiTraitInterfaceCallWithError(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn,
                lowerError: FfiConverterTypeDecryptionError_lower
            )
        }
    )

    /// Rust stores this pointer for future callback invocations, so it must live
    /// for the process lifetime (not just for the init function call).
    static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceDecryptionProvider> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceDecryptionProvider>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitDecryptionProvider() {
    uniffi_livekit_datatrack_fn_init_callback_vtable_decryptionprovider(UniffiCallbackInterfaceDecryptionProvider.vtablePtr)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeDecryptionProvider: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<DecryptionProvider>()

    typealias FfiType = UInt64
    typealias SwiftType = DecryptionProvider

    public static func lift(_ handle: UInt64) throws -> DecryptionProvider {
        if (handle & 1) == 0 {
            // Rust-generated handle, construct a new class that uses the handle to implement the
            // interface
            DecryptionProviderImpl(unsafeFromHandle: handle)
        } else {
            // Swift-generated handle, get the object from the handle map
            try handleMap.remove(handle: handle)
        }
    }

    public static func lower(_ value: DecryptionProvider) -> UInt64 {
        if let rustImpl = value as? DecryptionProviderImpl {
            // Rust-implemented object.  Clone the handle and return it
            rustImpl.uniffiCloneHandle()
        } else {
            // Swift object, generate a new vtable handle and return that.
            handleMap.insert(obj: value)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DecryptionProvider {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: DecryptionProvider, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeDecryptionProvider_lift(_ handle: UInt64) throws -> DecryptionProvider {
    try FfiConverterTypeDecryptionProvider.lift(handle)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeDecryptionProvider_lower(_ value: DecryptionProvider) -> UInt64 {
    FfiConverterTypeDecryptionProvider.lower(value)
}

/**
 * Provider for encrypting payloads for E2EE.
 */
public protocol EncryptionProvider: AnyObject, Sendable {
    /**
     * Encrypts the given payload being sent by the local participant.
     */
    func encrypt(payload: Bytes) throws -> EncryptedPayload
}

/**
 * Provider for encrypting payloads for E2EE.
 */
open class EncryptionProviderImpl: EncryptionProvider, @unchecked Sendable {
    fileprivate let handle: UInt64

    // Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public required init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public init(noHandle _: NoHandle) {
        handle = 0
    }

    #if swift(>=5.8)
        @_documentation(visibility: private)
    #endif
    public func uniffiCloneHandle() -> UInt64 {
        try! rustCall { uniffi_livekit_datatrack_fn_clone_encryptionprovider(self.handle, $0) }
    }

    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_livekit_datatrack_fn_free_encryptionprovider(handle, $0) }
    }

    /**
     * Encrypts the given payload being sent by the local participant.
     */
    open func encrypt(payload: Bytes) throws -> EncryptedPayload {
        try FfiConverterTypeEncryptedPayload_lift(rustCallWithError(FfiConverterTypeEncryptionError_lift) {
            uniffi_livekit_datatrack_fn_method_encryptionprovider_encrypt(
                self.uniffiCloneHandle(),
                FfiConverterTypeBytes_lower(payload), $0
            )
        })
    }
}

/// Put the implementation in a struct so we don't pollute the top-level namespace
private enum UniffiCallbackInterfaceEncryptionProvider {
    /// Create the VTable using a series of closures.
    /// Swift automatically converts these into C callback functions.
    ///
    /// Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceEncryptionProvider = .init(
        uniffiFree: { (uniffiHandle: UInt64) in
            do {
                try FfiConverterTypeEncryptionProvider.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface EncryptionProvider: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterTypeEncryptionProvider.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface EncryptionProvider: handle missing in uniffiClone")
            }
        },
        encrypt: { (
            uniffiHandle: UInt64,
            payload: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> EncryptedPayload in
                guard let uniffiObj = try? FfiConverterTypeEncryptionProvider.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.encrypt(
                    payload: FfiConverterTypeBytes_lift(payload)
                )
            }

            let writeReturn = { uniffiOutReturn.pointee = FfiConverterTypeEncryptedPayload_lower($0) }
            uniffiTraitInterfaceCallWithError(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn,
                lowerError: FfiConverterTypeEncryptionError_lower
            )
        }
    )

    /// Rust stores this pointer for future callback invocations, so it must live
    /// for the process lifetime (not just for the init function call).
    static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceEncryptionProvider> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceEncryptionProvider>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitEncryptionProvider() {
    uniffi_livekit_datatrack_fn_init_callback_vtable_encryptionprovider(UniffiCallbackInterfaceEncryptionProvider.vtablePtr)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeEncryptionProvider: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<EncryptionProvider>()

    typealias FfiType = UInt64
    typealias SwiftType = EncryptionProvider

    public static func lift(_ handle: UInt64) throws -> EncryptionProvider {
        if (handle & 1) == 0 {
            // Rust-generated handle, construct a new class that uses the handle to implement the
            // interface
            EncryptionProviderImpl(unsafeFromHandle: handle)
        } else {
            // Swift-generated handle, get the object from the handle map
            try handleMap.remove(handle: handle)
        }
    }

    public static func lower(_ value: EncryptionProvider) -> UInt64 {
        if let rustImpl = value as? EncryptionProviderImpl {
            // Rust-implemented object.  Clone the handle and return it
            rustImpl.uniffiCloneHandle()
        } else {
            // Swift object, generate a new vtable handle and return that.
            handleMap.insert(obj: value)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EncryptionProvider {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: EncryptionProvider, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeEncryptionProvider_lift(_ handle: UInt64) throws -> EncryptionProvider {
    try FfiConverterTypeEncryptionProvider.lift(handle)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeEncryptionProvider_lower(_ value: EncryptionProvider) -> UInt64 {
    FfiConverterTypeEncryptionProvider.lower(value)
}

/**
 * Encrypted payload and metadata required for decryption.
 */
public struct EncryptedPayload: Equatable, Hashable {
    public var payload: Bytes
    public var iv: InitializationVector
    public var keyIndex: UInt8

    /// Default memberwise initializers are never public by default, so we
    /// declare one manually.
    public init(payload: Bytes, iv: InitializationVector, keyIndex: UInt8) {
        self.payload = payload
        self.iv = iv
        self.keyIndex = keyIndex
    }
}

#if compiler(>=6)
    extension EncryptedPayload: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeEncryptedPayload: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EncryptedPayload {
        try EncryptedPayload(
            payload: FfiConverterTypeBytes.read(from: &buf),
            iv: FfiConverterTypeInitializationVector.read(from: &buf),
            keyIndex: FfiConverterUInt8.read(from: &buf)
        )
    }

    public static func write(_ value: EncryptedPayload, into buf: inout [UInt8]) {
        FfiConverterTypeBytes.write(value.payload, into: &buf)
        FfiConverterTypeInitializationVector.write(value.iv, into: &buf)
        FfiConverterUInt8.write(value.keyIndex, into: &buf)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeEncryptedPayload_lift(_ buf: RustBuffer) throws -> EncryptedPayload {
    try FfiConverterTypeEncryptedPayload.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeEncryptedPayload_lower(_ value: EncryptedPayload) -> RustBuffer {
    FfiConverterTypeEncryptedPayload.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/* 
 * Encoding used for frames pushed on a data track.
 *
 * The serialization format of the frame bytes (e.g. [`Protobuf`]); the structure
 * of those bytes is described by a schema, see [`DataTrackSchemaEncoding`].
 *
 * [`Protobuf`]: DataTrackFrameEncoding::Protobuf

 */

public enum DataTrackFrameEncoding: Equatable, Hashable {
    /**
     * ROS 1, must be described by a [`Ros1Msg`] schema.
     *
     * [`Ros1Msg`]: DataTrackSchemaEncoding::Ros1Msg
     */
    case ros1
    /**
     * CDR, must be described by a [`Ros2Msg`], [`Ros2Idl`], or [`OmgIdl`] schema.
     *
     * [`Ros2Msg`]: DataTrackSchemaEncoding::Ros2Msg
     * [`Ros2Idl`]: DataTrackSchemaEncoding::Ros2Idl
     * [`OmgIdl`]: DataTrackSchemaEncoding::OmgIdl
     */
    case cdr
    /**
     * Protocol Buffer, must be described by a [`Protobuf`] schema.
     *
     * [`Protobuf`]: DataTrackSchemaEncoding::Protobuf
     */
    case protobuf
    /**
     * FlatBuffer, must be described by a [`Flatbuffer`] schema.
     *
     * [`Flatbuffer`]: DataTrackSchemaEncoding::Flatbuffer
     */
    case flatbuffer
    /**
     * CBOR, self-describing.
     */
    case cbor
    /**
     * MessagePack, self-describing.
     */
    case msgpack
    /**
     * JSON, self-describing or described by a [`JsonSchema`] schema.
     *
     * [`JsonSchema`]: DataTrackSchemaEncoding::JsonSchema
     */
    case json
    /**
     * Another well-known encoding not known to this client version.
     */
    case other
    /**
     * An application-specific encoding identified by the contained string.
     *
     * Prefer using one of the well-known encodings unless the format is not enumerated.
     * The identifier must be non-empty and not exceed the server's length limit.

     */
    case custom(String)
}

#if compiler(>=6)
    extension DataTrackFrameEncoding: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeDataTrackFrameEncoding: FfiConverterRustBuffer {
    typealias SwiftType = DataTrackFrameEncoding

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DataTrackFrameEncoding {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return .ros1

        case 2: return .cdr

        case 3: return .protobuf

        case 4: return .flatbuffer

        case 5: return .cbor

        case 6: return .msgpack

        case 7: return .json

        case 8: return .other

        case 9: return try .custom(FfiConverterString.read(from: &buf))

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DataTrackFrameEncoding, into buf: inout [UInt8]) {
        switch value {
        case .ros1:
            writeInt(&buf, Int32(1))

        case .cdr:
            writeInt(&buf, Int32(2))

        case .protobuf:
            writeInt(&buf, Int32(3))

        case .flatbuffer:
            writeInt(&buf, Int32(4))

        case .cbor:
            writeInt(&buf, Int32(5))

        case .msgpack:
            writeInt(&buf, Int32(6))

        case .json:
            writeInt(&buf, Int32(7))

        case .other:
            writeInt(&buf, Int32(8))

        case let .custom(v1):
            writeInt(&buf, Int32(9))
            FfiConverterString.write(v1, into: &buf)
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeDataTrackFrameEncoding_lift(_ buf: RustBuffer) throws -> DataTrackFrameEncoding {
    try FfiConverterTypeDataTrackFrameEncoding.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeDataTrackFrameEncoding_lower(_ value: DataTrackFrameEncoding) -> RustBuffer {
    FfiConverterTypeDataTrackFrameEncoding.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/* 
 * Encoding used for a schema definition.
 *
 * Identifies the interface definition language the schema is written in (e.g. a
 * `.proto` file for [`Protobuf`]). This in turn dictates the wire format of the
 * frames the schema describes, captured by [`DataTrackFrameEncoding`].
 *
 * [`Protobuf`]: DataTrackSchemaEncoding::Protobuf

 */

public enum DataTrackSchemaEncoding: Equatable, Hashable {
    /**
     * Protocol Buffer IDL, describes [`Protobuf`] encoded frames.
     *
     * [`Protobuf`]: DataTrackFrameEncoding::Protobuf
     */
    case protobuf
    /**
     * FlatBuffer IDL, describes [`Flatbuffer`] encoded frames.
     *
     * [`Flatbuffer`]: DataTrackFrameEncoding::Flatbuffer
     */
    case flatbuffer
    /**
     * ROS 1 Message, describes [`Ros1`] encoded frames.
     *
     * [`Ros1`]: DataTrackFrameEncoding::Ros1
     */
    case ros1Msg
    /**
     * ROS 2 Message, describes [`Cdr`] encoded frames.
     *
     * [`Cdr`]: DataTrackFrameEncoding::Cdr
     */
    case ros2Msg
    /**
     * ROS 2 IDL, describes [`Cdr`] encoded frames.
     *
     * [`Cdr`]: DataTrackFrameEncoding::Cdr
     */
    case ros2Idl
    /**
     * OMG IDL, describes [`Cdr`] encoded frames.
     *
     * [`Cdr`]: DataTrackFrameEncoding::Cdr
     */
    case omgIdl
    /**
     * JSON Schema, describes [`Json`] encoded frames.
     *
     * [`Json`]: DataTrackFrameEncoding::Json
     */
    case jsonSchema
    /**
     * Another well-known encoding not known to this client version.
     */
    case other
    /**
     * An application-specific encoding identified by the contained string.
     *
     * Prefer using one of the well-known encodings unless the format is not enumerated.
     * The identifier must be non-empty and not exceed the server's length limit.

     */
    case custom(String)
}

#if compiler(>=6)
    extension DataTrackSchemaEncoding: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeDataTrackSchemaEncoding: FfiConverterRustBuffer {
    typealias SwiftType = DataTrackSchemaEncoding

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DataTrackSchemaEncoding {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return .protobuf

        case 2: return .flatbuffer

        case 3: return .ros1Msg

        case 4: return .ros2Msg

        case 5: return .ros2Idl

        case 6: return .omgIdl

        case 7: return .jsonSchema

        case 8: return .other

        case 9: return try .custom(FfiConverterString.read(from: &buf))

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DataTrackSchemaEncoding, into buf: inout [UInt8]) {
        switch value {
        case .protobuf:
            writeInt(&buf, Int32(1))

        case .flatbuffer:
            writeInt(&buf, Int32(2))

        case .ros1Msg:
            writeInt(&buf, Int32(3))

        case .ros2Msg:
            writeInt(&buf, Int32(4))

        case .ros2Idl:
            writeInt(&buf, Int32(5))

        case .omgIdl:
            writeInt(&buf, Int32(6))

        case .jsonSchema:
            writeInt(&buf, Int32(7))

        case .other:
            writeInt(&buf, Int32(8))

        case let .custom(v1):
            writeInt(&buf, Int32(9))
            FfiConverterString.write(v1, into: &buf)
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeDataTrackSchemaEncoding_lift(_ buf: RustBuffer) throws -> DataTrackSchemaEncoding {
    try FfiConverterTypeDataTrackSchemaEncoding.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeDataTrackSchemaEncoding_lower(_ value: DataTrackSchemaEncoding) -> RustBuffer {
    FfiConverterTypeDataTrackSchemaEncoding.lower(value)
}

public enum DataTrackSubscribeError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {
    case Unpublished(message: String)

    case Timeout(message: String)

    case Disconnected(message: String)

    case Internal(message: String)

    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if compiler(>=6)
    extension DataTrackSubscribeError: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeDataTrackSubscribeError: FfiConverterRustBuffer {
    typealias SwiftType = DataTrackSubscribeError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DataTrackSubscribeError {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return try .Unpublished(
                message: FfiConverterString.read(from: &buf)
            )

        case 2: return try .Timeout(
                message: FfiConverterString.read(from: &buf)
            )

        case 3: return try .Disconnected(
                message: FfiConverterString.read(from: &buf)
            )

        case 4: return try .Internal(
                message: FfiConverterString.read(from: &buf)
            )

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DataTrackSubscribeError, into buf: inout [UInt8]) {
        switch value {
        case .Unpublished(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(1))
        case .Timeout(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(2))
        case .Disconnected(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(3))
        case .Internal(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(4))
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeDataTrackSubscribeError_lift(_ buf: RustBuffer) throws -> DataTrackSubscribeError {
    try FfiConverterTypeDataTrackSubscribeError.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeDataTrackSubscribeError_lower(_ value: DataTrackSubscribeError) -> RustBuffer {
    FfiConverterTypeDataTrackSubscribeError.lower(value)
}

/**
 * An error indicating a payload could not be decrypted.
 */
public enum DecryptionError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {
    case Failed(reason: String)

    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if compiler(>=6)
    extension DecryptionError: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeDecryptionError: FfiConverterRustBuffer {
    typealias SwiftType = DecryptionError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DecryptionError {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return try .Failed(
                reason: FfiConverterString.read(from: &buf)
            )

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DecryptionError, into buf: inout [UInt8]) {
        switch value {
        case let .Failed(reason):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(reason, into: &buf)
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeDecryptionError_lift(_ buf: RustBuffer) throws -> DecryptionError {
    try FfiConverterTypeDecryptionError.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeDecryptionError_lower(_ value: DecryptionError) -> RustBuffer {
    FfiConverterTypeDecryptionError.lower(value)
}

/**
 * An error indicating a payload could not be encrypted.
 */
public enum EncryptionError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {
    case Failed(reason: String)

    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if compiler(>=6)
    extension EncryptionError: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeEncryptionError: FfiConverterRustBuffer {
    typealias SwiftType = EncryptionError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EncryptionError {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return try .Failed(
                reason: FfiConverterString.read(from: &buf)
            )

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: EncryptionError, into buf: inout [UInt8]) {
        switch value {
        case let .Failed(reason):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(reason, into: &buf)
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeEncryptionError_lift(_ buf: RustBuffer) throws -> EncryptionError {
    try FfiConverterTypeEncryptionError.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeEncryptionError_lower(_ value: EncryptionError) -> RustBuffer {
    FfiConverterTypeEncryptionError.lower(value)
}

/**
 * An error that can occur when publishing a data track.
 */
public enum PublishError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {
    /**
     * Local participant does not have permission to publish data tracks.
     *
     * Ensure the participant's token contains the `canPublishData` grant.

     */
    case NotAllowed(message: String)

    /**
     * A track with the same name is already published by the local participant.
     */
    case DuplicateName(message: String)

    /**
     * The track name is invalid.
     *
     * This occurs when the name is empty or exceeds the allowed maximum length.

     */
    case InvalidName(message: String)

    /**
     * Request to publish the track took long to complete.
     */
    case Timeout(message: String)

    /**
     * No additional data tracks can be published by the local participant.
     */
    case LimitReached(message: String)

    /**
     * Cannot publish data track when the room is disconnected.
     */
    case Disconnected(message: String)

    /**
     * Schema metadata is invalid.
     */
    case InvalidSchema(message: String)

    /**
     * Internal error, please report on GitHub.
     */
    case Internal(message: String)

    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if compiler(>=6)
    extension PublishError: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypePublishError: FfiConverterRustBuffer {
    typealias SwiftType = PublishError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PublishError {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return try .NotAllowed(
                message: FfiConverterString.read(from: &buf)
            )

        case 2: return try .DuplicateName(
                message: FfiConverterString.read(from: &buf)
            )

        case 3: return try .InvalidName(
                message: FfiConverterString.read(from: &buf)
            )

        case 4: return try .Timeout(
                message: FfiConverterString.read(from: &buf)
            )

        case 5: return try .LimitReached(
                message: FfiConverterString.read(from: &buf)
            )

        case 6: return try .Disconnected(
                message: FfiConverterString.read(from: &buf)
            )

        case 7: return try .InvalidSchema(
                message: FfiConverterString.read(from: &buf)
            )

        case 8: return try .Internal(
                message: FfiConverterString.read(from: &buf)
            )

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PublishError, into buf: inout [UInt8]) {
        switch value {
        case .NotAllowed(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(1))
        case .DuplicateName(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(2))
        case .InvalidName(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(3))
        case .Timeout(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(4))
        case .LimitReached(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(5))
        case .Disconnected(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(6))
        case .InvalidSchema(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(7))
        case .Internal(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(8))
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypePublishError_lift(_ buf: RustBuffer) throws -> PublishError {
    try FfiConverterTypePublishError.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypePublishError_lower(_ value: PublishError) -> RustBuffer {
    FfiConverterTypePublishError.lower(value)
}

/**
 * Reason why a data track frame could not be pushed.
 */
public enum PushFrameErrorReason: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {
    /**
     * Track is no longer published.
     */
    case TrackUnpublished(message: String)

    /**
     * Frame was dropped due to the pipeline queue being full.
     */
    case QueueFull(message: String)

    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if compiler(>=6)
    extension PushFrameErrorReason: Sendable {}
#endif

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypePushFrameErrorReason: FfiConverterRustBuffer {
    typealias SwiftType = PushFrameErrorReason

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PushFrameErrorReason {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return try .TrackUnpublished(
                message: FfiConverterString.read(from: &buf)
            )

        case 2: return try .QueueFull(
                message: FfiConverterString.read(from: &buf)
            )

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PushFrameErrorReason, into buf: inout [UInt8]) {
        switch value {
        case .TrackUnpublished(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(1))
        case .QueueFull(_ /* message is ignored*/ ):
            writeInt(&buf, Int32(2))
        }
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypePushFrameErrorReason_lift(_ buf: RustBuffer) throws -> PushFrameErrorReason {
    try FfiConverterTypePushFrameErrorReason.lift(buf)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypePushFrameErrorReason_lower(_ value: PushFrameErrorReason) -> RustBuffer {
    FfiConverterTypePushFrameErrorReason.lower(value)
}

/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias InitializationVector = Data

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public struct FfiConverterTypeInitializationVector: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> InitializationVector {
        try FfiConverterData.read(from: &buf)
    }

    public static func write(_ value: InitializationVector, into buf: inout [UInt8]) {
        FfiConverterData.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> InitializationVector {
        try FfiConverterData.lift(value)
    }

    public static func lower(_ value: InitializationVector) -> RustBuffer {
        FfiConverterData.lower(value)
    }
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeInitializationVector_lift(_ value: RustBuffer) throws -> InitializationVector {
    try FfiConverterTypeInitializationVector.lift(value)
}

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
public func FfiConverterTypeInitializationVector_lower(_ value: InitializationVector) -> RustBuffer {
    FfiConverterTypeInitializationVector.lower(value)
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}

/// Use a global variable to perform the versioning checks. Swift ensures that
/// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_livekit_datatrack_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if uniffi_livekit_datatrack_checksum_method_decryptionprovider_decrypt() != 1225 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_livekit_datatrack_checksum_method_encryptionprovider_encrypt() != 40311 {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitDecryptionProvider()
    uniffiCallbackInitEncryptionProvider()
    uniffiEnsureLivekitCommonInitialized()
    return InitializationResult.ok
}()

/// Make the ensure init function public so that other modules which have external type references to
/// our types can call it.
public func uniffiEnsureLivekitDatatrackInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all
